title: Mackenzie Arts
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: "&copy; 2020 Mackenzie Arts Council."

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav_links:
  Events: /events/
  Calendar: /calendar/
  Blog: /blog/
  About: /about/
  Gallery: /gallery/
  Departments: /departments/
