title: Mackenzie Arts
description: >-
  WLMAC Arts Council events and information.
baseurl: "" # TODO: Remove when migrating to domain
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: "&copy; 2020 Mackenzie Arts Council."

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# For the phone filter plugin
phone_ext_marker: "ext."
phone_delimiter: "."

nav_links:
  - name: Events
    url: /events/
  - name: Calendar
    url: /calendar/
  - name: Announcements
    url: /announcements/
    children:
    - name: Music
      url: /announcements/music/
    - name: Drama
      url: /announcements/drama/
    - name: Dance
      url: /announcements/dance/
    - name: Visual & Digital Arts
      url: /announcements/visual-arts/
  - name: About
    url: /about/
  - name: Gallery
    url: /gallery/
  - name: Departments
    children:
    - name: Music
      url: /departments/music/
    - name: Drama
      url: /departments/drama/
    - name: Dance
      url: /departments/dance/
    - name: Visual & Digital Arts
      url: /departments/visual-arts/

collections:
  announcements:
    output: true
    permalink: /announcements/:name/
  departments:
    output: true
    permalink: /departments/:name/
  event_pages:
    output: true
    permalink: /events/:name/
    order:
      - central-arts-council.html
      - music.html
      - drama.html
      - dance.html
      - visual-arts.html
  galleries:
    output: true
    permalink: /gallery/:name/
    order:
      - music.md
      - drama.md
      - dance.md
      - visual-arts.md
  classwork:
    output: true
    permalink: /classwork/:name/
    order:
      - music.md
      - drama.md
      - dance.md
      - visual-arts.md

defaults:
  - scope:
      path: "_announcements"
    values:
      title: Announcements
      layout: "announcements"
      subheading: "Announcements Page"
  - scope:
      path: "_departments"
    values:
      layout: "department"
      subheading: "Department Page"
  - scope:
      path: "_event_pages"
    values:
      heading: "Events"
  - scope:
      path: "_galleries"
    values:
      layout: "gallery-display"
      heading: "Gallery"
  - scope:
      path: "_classwork"
    values:
      layout: "gallery-display"
      heading: "Classwork"
  - scope:
      path: "_posts"
    values:
      layout: "post"

  # For display pages
  - scope:
      path: "assets/img/dance"
    values:
      tag: "dance"
  - scope:
      path: "assets/img/drama"
    values:
      tag: "drama"
  - scope:
      path: "assets/img/music"
    values:
      tag: "music"
  - scope:
      path: "assets/img/visual-arts"
    values:
      tag: "visual"
  - scope:
      path: "assets/img/classwork/dance"
    values:
      tag: "dance-work"
  - scope:
      path: "assets/img/classwork/drama"
    values:
      tag: "drama-work"
  - scope:
      path: "assets/img/classwork/music"
    values:
      tag: "music-work"
  - scope:
      path: "assets/img/classwork/visual-arts"
    values:
      tag: "visual-work"
