title: Mackenzie Arts
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/MacArts" # TODO: Remove when migrating to domain
url: "" # the base hostname & protocol for your site, e.g. http://example.com
copyright: "&copy; 2020 Mackenzie Arts Council."

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

nav_links:
  Events: /events/
  Calendar: /calendar/
  Blog: /blog/
  About: /about/
  Gallery: /gallery/
  Departments:
    Visual & Digital Arts: /departments/visual-arts/
    Dance: /departments/dance/
    Drama: /departments/drama/
    Music: /departments/music/

collections:
  galleries:
    output: true
    permalink: /gallery/:name/

defaults:
  - scope:
      path: "assets/img/dance"
    values:
      tag: "dance"
  - scope:
      path: "assets/img/drama"
    values:
      tag: "drama"
  - scope:
      path: "assets/img/music"
    values:
      tag: "music"
  - scope:
      path: "assets/img/visualarts"
    values:
      tag: "visual"
  - scope:
      path: "_galleries"
    values:
      layout: "gallery-display"
      heading: "Gallery"
