backend:
  name: git-gateway
  branch: netlify-cms
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    label_singular: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'config',
          file: 'members',
          search_fields: ['members.*.display_name'],
          value_field: 'members.*.display_name',
          min: 1
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          multiple: true,
          options: [
            { label: 'Dance', value: 'dance' },
            { label: 'Music', value: 'music' },
            { label: 'Visual Arts', value: 'visual-arts' },
            { label: 'Drama', value: 'drama' },
          ]
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Authors'
        name: 'members'
        file: '_data/members.yml'
        fields:
          - label: 'Authors'
            name: 'authors'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Image', name: 'headshot', widget: 'image', allow_multiple: false, required: false }
              - { label: 'Council', name: 'council', widget: 'string' }
              - { label: 'Position', name: 'position', widget: 'string' }
              - { label: 'Bio', name: 'bio', widget: 'text' }