backend:
  name: git-gateway
  branch: netlify-cms
media_folder: '/assets/img'
logo_url: 'https://wlmacarts.netlify.app/assets/img/logo.svg'
collections:
  - name: 'blog'
    label: 'Blog'
    label_singular: 'Post'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'config',
          file: 'members',
          search_fields: ['members.*.name'],
          value_field: 'members.*.name',
          min: 1
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'select',
          multiple: true,
          options: [
            { label: 'Dance', value: 'dance' },
            { label: 'Music', value: 'music' },
            { label: 'Visual Arts', value: 'visual-arts' },
            { label: 'Drama', value: 'drama' },
          ]
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Authors'
        name: 'members'
        file: '_data/members.yml'
        fields:
          - label: 'Members'
            name: 'members'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Image', name: 'headshot', widget: 'image', allow_multiple: false, required: false, media_folder: '{{media_folder}}/members' }
              - { label: 'Council', name: 'council', widget: 'string' }
              - { label: 'Position', name: 'position', widget: 'string' }
              - { label: 'Bio', name: 'bio', widget: 'text' }
  - name: 'galleries'
    label: 'Galleries'
    editor:
      preview: false
    files:
      - label: 'Dance'
        name: 'dance'
        file: 'tmp/dance'
        fields:
          - {
            label: 'Gallery',
            name: 'gallery',
            widget: 'image',
            media_folder: '{{media_folder}}/dance',
            required: false
          }
          - {
            label: 'Classwork',
            name: 'classwork',
            widget: 'image',
            media_folder: '{{media_folder}}/classwork/dance',
            required: false
          }
      - label: 'Music'
        name: 'music'
        file: 'tmp/music'
        fields:
          - {
            label: 'Gallery',
            name: 'gallery',
            widget: 'image',
            media_folder: '{{media_folder}}/music',
            required: false
          }
          - {
            label: 'Classwork',
            name: 'classwork',
            widget: 'image',
            media_folder: '{{media_folder}}/classwork/music',
            required: false
          }
      - label: 'Drama'
        name: 'drama'
        file: 'tmp/drama'
        fields:
          - {
            label: 'Gallery',
            name: 'gallery',
            widget: 'image',
            media_folder: '{{media_folder}}/drama',
            required: false
          }
          - {
            label: 'Classwork',
            name: 'classwork',
            widget: 'image',
            media_folder: '{{media_folder}}/classwork/drama',
            required: false
          }
      - label: 'Visual Arts'
        name: 'visual-arts'
        file: 'tmp/visual-arts'
        fields:
          - {
            label: 'Gallery',
            name: 'gallery',
            widget: 'image',
            media_folder: '{{media_folder}}/visual-arts',
            required: false
          }
          - {
            label: 'Classwork',
            name: 'classwork',
            widget: 'image',
            media_folder: '{{media_folder}}/classwork/visual-arts',
            required: false
          }
  - name: 'events'
    label: 'Events'
    editor:
      preview: false
    files:
      - label: 'Events'
        name: 'events'
        file: '_data/events.yml'
        fields:
          - label: 'Central Arts Council'
            label_singular: 'Event'
            name: 'central'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
          - label: 'Music'
            label_singular: 'Event'
            name: 'music'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
          - label: 'Drama'
            label_singular: 'Event'
            name: 'drama'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
          - label: 'Dance'
            label_singular: 'Event'
            name: 'dance'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
          - label: 'Visual Arts'
            label_singular: 'Event'
            name: 'visual-arts'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'markdown' }
              - { label: 'Image', name: 'image', widget: 'image', allow_multiple: false }
  - name: 'departments'
    label: 'Departments'
    editor:
      preview: false
    files:
      - label: 'Music'
        name: 'music'
        file: '_data/departments/music.yml'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'hidden', default: 'Music' }
          - { label: 'Name', name: 'name', widget: 'hidden', default: 'Music' }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Classwork'
            name: 'classwork'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Contact'
            name: 'contact'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Room', name: 'room', widget: 'string' }
      - label: 'Drama'
        name: 'drama'
        file: '_data/departments/drama.yml'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'hidden', default: 'Drama' }
          - { label: 'Name', name: 'name', widget: 'hidden', default: 'Drama' }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Classwork'
            name: 'classwork'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Contact'
            name: 'contact'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Room', name: 'room', widget: 'string' }
      - label: 'Dance'
        name: 'dance'
        file: '_data/departments/dance.yml'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'hidden', default: 'Dance' }
          - { label: 'Name', name: 'name', widget: 'hidden', default: 'Dance' }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Classwork'
            name: 'classwork'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Contact'
            name: 'contact'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Room', name: 'room', widget: 'string' }
      - label: 'Visual & Digital Arts'
        name: 'visual-arts'
        file: '_data/departments/visual-arts.yml'
        fields:
          - { label: 'Heading', name: 'heading', widget: 'hidden', default: 'Visual & Digital Arts' }
          - { label: 'Name', name: 'name', widget: 'hidden', default: 'Visual Arts' }
          - label: 'Gallery'
            name: 'gallery'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Classwork'
            name: 'classwork'
            widget: 'object'
            fields:
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Image', name: 'image', widget: 'image', media_folder: '{{media_folder}}/music' }
              - { label: 'Alt Text', name: 'alt-text', widget: 'string' }
          - label: 'Contact'
            name: 'contact'
            widget: 'list'
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Email', name: 'email', widget: 'string' }
              - { label: 'Phone', name: 'phone', widget: 'string' }
              - { label: 'Room', name: 'room', widget: 'string' }
